apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: base
    repoURL: mcr.microsoft.com/oss/helmchart/istio
    targetRevision: 1.21.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: istiod
    repoURL: mcr.microsoft.com/oss/helmchart/istio
    targetRevision: 1.21.0
    helm:
      parameters:
      - name: "pilot.resources.requests.cpu"
        value: 500m
      - name: "pilot.resources.requests.memory"
        value: 2048Mi
      - name: "meshConfig.outboundTrafficPolicy.mode"
        value: REGISTRY_ONLY
      - name: "meshConfig.accessLogFile"
        value: /dev/stdout
      - name: "pilot.istio_cni.enabled"
        value: "true"
      - name: "pilot.hub"
        value: mcr.microsoft.com/oss/istio
      - name: "pilot.variant"
        value: distroless
      - name: "global.hub"
        value: mcr.microsoft.com/oss/istio
      - name: "global.variant"
        value: distroless
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: cni
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.21.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  project: default
  source:
    chart: gateway
    repoURL: mcr.microsoft.com/oss/helmchart/istio
    targetRevision: 1.21.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-egress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-egress
  project: default
  source:
    chart: gateway
    repoURL: mcr.microsoft.com/oss/helmchart/istio
    targetRevision: 1.21.0
    helm:
      parameters:
        - name: "name"
          value: istio-egressgateway
        - name: "service.type"
          value: ClusterIP
        - name: "nodeSelector.egress"
          value: enabled
        - name: "tolerations[0].key"
          value: "egress"
        - name: "tolerations[0].operator"
          value: "Equal"
        - name: "tolerations[0].value"
          value: "enabled"
        - name: "tolerations[0].effect"
          value: "NoSchedule"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
