apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-configs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  project: default
  source:
    repoURL: https://github.com/nshankar13/tutorials.git
    path: istio-secure-demo/istio-configs
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
