apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SidecarHostsAndTrafficPolicy
metadata:
  name: sidecar
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - networking.istio.io
      kinds:
      - Sidecar
