apiVersion: constraints.gatekeeper.sh/v1beta1
kind: MeshSidecarHosts
metadata:
  name: mesh-level-sidecar
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
  parameters:
    requiredHosts:
    - "istio-egress/*"
    - "istio-system/*"
    - "./*"
